import type { MoveDefinition } from "@/components/CharacterSheet/Move";
import type { PlaybookType } from "@/types";

export const PLAYBOOK_MOVES: Partial<Record<PlaybookType, MoveDefinition[]>> = {
  'would-be-hero': [
    {
      id: 'wbh-anger-is-a-gift',
      name: 'Anger is a Gift',
      selectable: true,
      startingMove: true,
      uses: 2,
      triggerOverride: 'When you **burn with righteous anger** (see Fear & Anger on back of playbook), hold 2 Resolve. You can spend your Resolve 1-for-1 to:',
      list: [
        'Set aside fear and doubt to do what must be done',
        'Act suddenly, catching them off-guard',
        'Inspire allies or bystanders to follow your lead',
        'Strike hard (+1d4 damage, *forceful*)',
        'Keep your footing, position, and/or your course despite what befalls you',
      ],
    },
    {
      id: 'wbh-potential-for-greatness',
      name: 'Potential for Greatness',
      selectable: true,
      startingMove: true,
      requires: ['wbh-anger-is-a-gift'],
      triggerOverride: 'Once per level, **when you roll a stat and get a 10+**, mark one of the following (note the level during which you marked it). You don\'t have to mark them in order.',
      checkList: [
        'Increase the stat you rolled by 1, to a max of +2 (at level ___)',
        'Increase the stat you rolled by 1, to a max of +2 (at level ___)',
        'Increase the stat you rolled by 1, to a max of +2 (at level ___)',
        'Increase the stat you rolled by 1, to a max of +2 (at level ___)',
        'Increase your max HP by 4 (at level ___)',
        'Increase your damage die to a d8 (at level ___)',
      ],
      checkListIds: ['pfg-stat-1', 'pfg-stat-2', 'pfg-stat-3', 'pfg-stat-4', 'pfg-hp', 'pfg-damage'],
      checkListLeveled: true,
    },
    {
      id: 'wbh-speak-truth-to-power',
      name: 'Speak Truth to Power',
      selectable: true,
      requires: ['wbh-anger-is-a-gift'],
      triggerOverride: 'When you **demand that someone does what is clearly good and right**, you have advantage to Persuade. If they refuse, gain +1 Resolve.',
    },
    {
      id: 'wbh-better-part-of-valor',
      name: 'Better Part of Valor',
      selectable: true,
      triggerOverride: 'When you **are outnumbered or facing a foe bigger than you**, you have advantage to hide from, escape from, or sneak past them.',
    },
    {
      id: 'wbh-i-get-knocked-down',
      name: 'I Get Knocked Down',
      selectable: true,
      triggerOverride: 'When you **take damage despite your best efforts to avoid it**, you can choose to halve the damage but pick 1 of the following:',
      list: [
        'You lose something (footing, grip, etc.)',
        'Something on your person breaks',
        "You're out of it for a moment",
      ],
      footer: 'Whatever you choose, the GM will describe the details.',
    },
    {
      id: 'wbh-but-i-get-up-again',
      name: 'But I Get Up Again',
      selectable: true,
      requires: ['wbh-i-get-knocked-down'],
      triggerOverride: 'When you **use I Get Knocked Down**, you have advantage on your next roll against whatever dealt the damage and your next blow against them does +1d4 damage.',
    },
    {
      id: 'wbh-improved-stat',
      name: 'Improved Stat',
      selectable: true,
      takes: 2,
      body: 'Each time you take this move, increase one of your stats by 1 (to a max of +2).',
    },
    {
      id: 'wbh-in-over-your-head',
      name: 'In Over Your Head',
      selectable: true,
      triggerOverride: 'When **another PC rescues you from danger**, mark XP.',
    },
    {
      id: 'wbh-iron-will',
      name: 'Iron Will',
      selectable: true,
      triggerOverride: 'When you **are subject to mind control or magic that affects your feelings**, you can take 1d4 damage (ignoring armor) to disregard its influence.',
    },
    {
      id: 'wbh-inquiring-minds',
      name: 'Inquiring Minds',
      selectable: true,
      triggerOverride: 'When you **seek out and receive honest advice**, gain advantage on your next roll to follow that advice.',
    },
    {
      id: 'wbh-never-gonna-keep-me-down',
      name: 'Never Gonna Keep Me Down',
      selectable: true,
      uses: 1,
      triggerOverride: 'When you **have 5 or fewer current HP**, you impose disadvantage on any damage you take.',
      footer: "Once per session, when you are at Death's Door, don't roll. You get a 10+.",
    },
    {
      id: 'wbh-resourceful',
      name: 'Resourceful',
      selectable: true,
      triggerOverride: 'When you **Defy Danger and roll a 6–**, ask the GM a question from Seek Insight after they describe what happens. Gain advantage on your next roll to act on the answer.',
    },
    {
      id: 'wbh-something-to-remember-me-by',
      name: 'Something to Remember Me By',
      selectable: true,
      triggerOverride: 'When you **spend Readiness (from Defend) to strike back at an attacker**, you deal +1d4 damage and scar, mark, or diminish them in some way (the GM will say how, or ask you to).',
    },
    {
      id: 'wbh-tough-love',
      name: 'Tough Love',
      selectable: true,
      triggerOverride: 'When you **honestly think another PC is in the wrong and call them on it**, they have disadvantage on any rolls against you until you two work it out.',
    },
    {
      id: 'wbh-underestimated',
      name: 'Underestimated',
      selectable: true,
      body: [
        'As long as you **avoid overt hostility**, no enemy will consider you a threat.',
        'When you **first make your move against an enemy who underestimates you**, you have advantage.',
      ],
    },
    {
      id: 'wbh-up-with-people',
      name: 'Up With People',
      selectable: true,
      uses: 2,
      uses2: 1,
      triggerOverride: 'When you **converse with someone** (PC or NPC) you can hold 2 Rapport with them. If you do, they hold 1 Rapport with you. During the conversation, either of you can spend 1 Rapport to ask the other player one of the following and get an honest answer.',
      list: [
        'What weighs you down or holds you back?',
        'What drives you forward?',
        'What lesson would you have me learn?',
        'What do you think of me, truly?',
      ],
    },
    {
      id: 'wbh-versatile',
      name: 'Versatile',
      selectable: true,
      requiresLevel: 2,
      requires: ['wbh-potential-for-greatness'],
      takes: 4,
      body: 'Choose a move from any other playbook, as long as you meet its requirements. You can pick a different playbook each time. You can\'t take Improved Stat or Superior Stat.',
    },
    {
      id: 'wbh-a-force-to-be-reckoned-with',
      name: 'A Force to Be Reckoned With',
      selectable: true,
      requires: ['wbh-underestimated'],
      requiresLevel: 6,
      triggerOverride: 'When you **Defy Danger against something trying to harm or constrain you**, on a 12+ you turn the tables on them (the GM will say how, or ask you to).',
      footer: 'Any intelligent creature who looks you in the eye or hears the steel in your voice instinctively knows that you are a force to be reckoned with, and treats you appropriately.',
    },
    {
      id: 'wbh-big-damn-hero',
      name: 'Big Damn Hero',
      selectable: true,
      requires: ['wbh-in-over-your-head'],
      requiresLevel: 6,
      triggerOverride: "When you **first leap into danger to protect someone**, don't roll to Defend. Instead, treat it as though you rolled a 10+.",
      footer: 'When you **Defend**, you can spend 1 Readiness to lock eyes with an attacker; they have disadvantage on damage rolls against you and your ward for the rest of the fight.',
    },
    {
      id: 'wbh-superior-stat',
      name: 'Superior Stat',
      selectable: true,
      requiresLevel: 6,
      body: 'Requires all 6 marks in Potential for Greatness. Increase one of your stats by +1 (to a max of +3).',
    },
    {
      id: 'wbh-undaunted',
      name: 'Undaunted',
      selectable: true,
      requires: ['wbh-better-part-of-valor'],
      requiresLevel: 6,
      triggerOverride: 'When you **are outnumbered or facing a foe bigger than you**, you get +1 armor and deal +1d6 damage.',
    },
    {
      id: 'wbh-voice-of-experience',
      name: 'Voice of Experience',
      selectable: true,
      requires: ['wbh-inquiring-minds'],
      requiresLevel: 6,
      triggerOverride: 'When **another PC comes to you for advice and you tell them what you think is best**, they have advantage on their first roll to follow your advice.',
      footer: 'When you **Seek Insight**, you can always ask, "What is about to happen?" for free, even on a 6–.',
    },
  ],
  blessed: [
    {
      id: 'blessed-amulets-and-talismans',
      name: 'Amulets & Talismans',
      selectable: true,
      triggerOverride: 'When you **craft a protective charm for someone**, spend 1 Stock and name a source of harm (fire, stabbing, etc.). When they **would suffer such harm while bearing your charm**, roll +INT: **on a 10+**, they ignore the harm entirely; **on a 7-9**, they suffer only half the damage or effect; **on a 6-**, they suffer the harm normally. One can benefit from only 1 charm at a time, and it loses its potency after 1 use.',
    },
    {
      id: 'blessed-barkskin',
      name: 'Barkskin',
      selectable: true,
      triggerOverride: 'When you **are touching the earth**, you have 2 armor. When you **mark another with 1 Stock**, they gain this benefit so long as the mark remains.',
    },
    {
      id: 'blessed-big-magic',
      name: 'Big Magic',
      selectable: true,
      takes: 2,
      body: 'Each time you take this move, choose an additional remarkable trait for your sacred pouch and increase your max Stock by 2.',
    },
    {
      id: 'blessed-borrow-power',
      name: 'Borrow Power',
      selectable: true,
      requires: ['blessed-spirit-tongue'],
      triggerOverride: 'When **a spirit or beast loans you power**, ask the GM for one of its tags or moves. Store it in your pouch in place of 1 Stock. When you **use the borrowed tag or move**, roll +WIS: **on a 10+**, you do it and can use the power again; **on a 7-9**, you do it, but lose the power.',
    },
    {
      id: 'blessed-call-the-spirits',
      name: 'Call the Spirits',
      selectable: true,
      startingMove: true,
      requires: ['blessed-spirit-tongue'],
      trigger: 'spend 1 Stock and perform a short rite',
      footer: 'the spirit(s) of a place or object manifest and hear you out. What they do next is up to them.',
    },
    {
      id: 'blessed-danus-grasp',
      name: "Danu's Grasp",
      selectable: true,
      triggerOverride: "When you **call on the world itself to bind a spirit or a perversion of nature**, spend 1 Stock and roll +WIS: **on a 7+**, roots, vines, and earth pull at them, and they pick 1; **on a 10+**, as a 7-9, but both apply.",
      list: [
        "They're restrained, unable to act freely until your focus slips or they tear their way free",
        'They take 2d4 damage (ignores armor)',
      ],
      footer: 'If this brings them to 0 HP, they are pulled into the earth and bound in rune-etched stone.',
    },
    {
      id: 'blessed-healers-arts',
      name: "Healer's Arts",
      selectable: true,
      triggerOverride: 'When **someone Recovers under your care**, they recover (extra) HP equal to your WIS. If you **also spend 1 Stock**, they heal an extra 5 HP and their wounds/injuries are stabilized.',
    },
    {
      id: 'blessed-heed-my-words',
      name: 'Heed My Words',
      selectable: true,
      triggerOverride: 'When you **Persuade by talking sense or warning against foolishness**, you have advantage.',
    },
    {
      id: 'blessed-improved-stat',
      name: 'Improved Stat',
      selectable: true,
      takes: 2,
      body: 'Each time you take this move, increase one of your stats by 1 (to a max of +2).',
    },
    {
      id: 'blessed-into-the-lions-den',
      name: "Into the Lion's Den",
      selectable: true,
      triggerOverride: 'When you **approach a beast calmly and show no fear**, it will not harm you (though it may threaten you and test your nerve). When you **lay your hand gently upon a beast**, it calms to your touch.',
    },
    {
      id: 'blessed-lightning-rod',
      name: 'Lightning Rod',
      selectable: true,
      triggerOverride: 'When you **Defend while touching the earth**, you can spend 1 Readiness to intercept a nearby magical attack and redirect it harmlessly into the ground.',
    },
    {
      id: 'blessed-natures-wrath',
      name: "Nature's Wrath",
      selectable: true,
      requires: ['blessed-danus-grasp'],
      requiresLevel: 6,
      body: "Danu's Grasp gains the area tag and can affect any creature. A mortal reduced to 0 HP is subdued or killed (your choice) rather than bound in stone.",
    },
    {
      id: 'blessed-potent-workings',
      name: 'Potent Workings',
      selectable: true,
      requires: ['blessed-amulets-and-talismans'],
      requiresLevel: 6,
      triggerOverride: 'When you **craft a protective charm**, you may spend 1 additional Stock to choose 1:',
      list: [
        'Name an additional type of harm',
        'On a 10+, the charm retains its potency',
      ],
    },
    {
      id: 'blessed-rites-of-the-land',
      name: 'Rites of the Land',
      selectable: true,
      uses: 4,
      triggerOverride: 'Once per season, when you **oversee the sacred rites**, hold 1 Favor. If you also sacrifice 1 Surplus, hold 4 Favor instead. Spend Favor in lieu of Stock, 1-for-1.',
      footer: 'When you **publicly sacrifice something or someone much-loved**, either clear a steading debility or gain advantage when the steading next rolls +Fortunes.',
    },
    {
      id: 'blessed-shared-souls',
      name: 'Shared Souls',
      selectable: true,
      requires: ['blessed-into-the-lions-den'],
      requiresLevel: 6,
      triggerOverride: 'When you **mark a beast with 1 Stock**, you can direct its actions and perceive through its senses no matter the distance between you. Treat it as a follower with 3 Loyalty; when you spend its last Loyalty, the effect ends.',
    },
    {
      id: 'blessed-spirit-tongue',
      name: 'Spirit Tongue',
      selectable: true,
      startingMove: true,
      body: 'You can speak with beasts and spirits. You can always ask the GM, "What spirits are active here?" and get an honest answer.',
    },
    {
      id: 'blessed-suck-the-poison-out',
      name: 'Suck the Poison Out',
      selectable: true,
      requires: ['blessed-healers-arts'],
      requiresLevel: 6,
      triggerOverride: "When you **draw a malady from a patient's body, mind, or soul**, spend 1 Stock and roll +WIS: **on a 10+**, you remove the malady and can safely discard it or store it in your sacred pouch (taking the space of 1 Stock) to study or inflict on another; **on a 7-9**, you remove it, but choose 1:",
      list: [
        'Your patient suffers lingering harm or trauma',
        "You suffer some of the malady's effects",
        'It will be harmful and dangerous to discard',
      ],
    },
    {
      id: 'blessed-superior-stat',
      name: 'Superior Stat',
      selectable: true,
      requiresLevel: 6,
      body: 'Increase one of your stats by +1 (to a max of +3).',
    },
    {
      id: 'blessed-trackless-step',
      name: 'Trackless Step',
      selectable: true,
      triggerOverride: 'When you **move through nature with care and patience**, you make no sound, leave no trace and can ignore any hindering or treacherous terrain (briars, mire, scree, etc.). When you **spend 1 Stock and mark others**, they each gain this benefit so long as the mark remains. 1 Stock can mark a number of individuals up to your level +INT.',
    },
    {
      id: 'blessed-veil',
      name: 'Veil',
      selectable: true,
      triggerOverride: 'When you **wrap yourself or another in a subtle veil**, spend 1 Stock and choose 1:',
      list: [
        'A type of being you name (including "people") will tend to ignore your presence',
        "People will perceive you as someone else, though you must wear something of an individual's in order to impersonate them",
      ],
      footer: 'When **your deception comes under scrutiny**, roll +INT: **on a 10+**, the veil holds, and no one is the wiser; **on a 7-9**, the veil holds, but there is further scrutiny or a complication (GM\'s choice).',
    },
    {
      id: 'blessed-voice-of-the-earth-mother',
      name: 'Voice of the Earth Mother',
      selectable: true,
      requires: ['blessed-spirit-tongue'],
      requiresLevel: 6,
      triggerOverride: 'When you **speak on behalf of Danu**, natural beasts and spirits of the wild respect your authority. All but the most headstrong will do as you command, even against their instincts.',
    },
    {
      id: 'blessed-wards-and-bindings',
      name: 'Wards & Bindings',
      selectable: true,
      triggerOverride: 'When you **mark a boundary with sacred signs**, spend 1 Stock and describe who or what they affect (using no more words than your level). Also, choose whether the affected beings are repelled or trapped by the signs.',
      footer: 'When **your wards or bindings are first tested**, roll +INT: **on a 10+**, they will hold as long as the signs remain unmarred (and the affected creature can do nothing to affect them directly); **on a 7-9**, they hold for now but may be overcome through might or will.',
    },
    {
      id: 'blessed-wild-soul',
      name: 'Wild Soul',
      selectable: true,
      requiresLevel: 2,
      body: "Each time you take this move, gain a Ranger move of your choice for which you qualify. You can't pick Improved Stat or Superior Stat.",
    },
  ],
  seeker: [
    {
      id: 'seeker-well-versed',
      name: 'Well Versed',
      selectable: true,
      startingMove: true,
      takes: 2,
      body: 'Mark 1 topic, in addition to the one noted in your Background. Each additional time you take this move, mark 2 more topics.',
      checkList: [
        'The Last Door, death, and the undead',
        'The civilizations of humanity',
        'The Fae and their strange ways',
        'The Makers and their arts',
        'The primordial powers',
        'The Things Below',
        'The wild world and its spirits',
      ],
      checkListIds: [
        'sk-wv-last-door',
        'sk-wv-civilizations',
        'sk-wv-fae',
        'sk-wv-makers',
        'sk-wv-primordial',
        'sk-wv-things-below',
        'sk-wv-wild-world',
      ],
      footer: 'When you **Know Things about one of your topics**, you can ask the GM a follow-up question of your choice (even on a 6-).',
    },
    {
      id: 'seeker-work-with-what-youve-got',
      name: "Work With What You've Got",
      selectable: true,
      startingMove: true,
      triggerOverride: 'When you **cleverly use your environment to harm or impede your foe(s)**, roll +INT: **on a 10+**, pick 2; **on a 7-9**, pick 1:',
      list: [
        'Interrupt or thwart their action(s)',
        'Create an opportunity that grants you or an ally advantage on the next roll to exploit it',
        "Deal damage appropriate to the source (d4 for bruises/scrapes, d6 for bloodshed, d8 if it'd break bones, d10 if it'd kill a common person)",
      ],
    },
    {
      id: 'seeker-attuned',
      name: 'Attuned',
      selectable: true,
      triggerOverride: 'When you **Seek Insight**, you can always ask, "What here is infused with magic?" for free, even on a 6-.',
    },
    {
      id: 'seeker-conduit-of-power',
      name: 'Conduit of Power',
      selectable: true,
      uses: 3,
      triggerOverride: 'When you **would mark a Consequence from a major arcanum**, you can mark 1 box here instead, with no negative effect. (These marks never clear.)',
    },
    {
      id: 'seeker-countermeasures',
      name: 'Countermeasures',
      selectable: true,
      triggerOverride: 'When you **witness a magical effect**, you may ask the GM, "how can this be countered or interrupted?" and get an honest answer. You or an ally gain advantage on your next roll to act on the answer.',
    },
    {
      id: 'seeker-everything-bleeds',
      name: 'Everything Bleeds',
      selectable: true,
      triggerOverride: "When you **exploit an unnatural foe's specific weakness or vulnerability**, deal +1d6 damage.",
    },
    {
      id: 'seeker-everything-burns',
      name: 'Everything Burns',
      selectable: true,
      triggerOverride: 'When you **inspect a work of artifice or magic for a fatal flaw**, roll +INT: **on a 7+**, the GM will reveal the best way to destroy/sabotage it; **on a 10+**, you or an ally also gain advantage to act on the info.',
    },
    {
      id: 'seeker-improved-stat',
      name: 'Improved Stat',
      selectable: true,
      takes: 2,
      body: 'Each time you take this move, increase one of your stats by 1 (to a max of +2).',
    },
    {
      id: 'seeker-initiate-of-the-secret-arts',
      name: 'Initiate of the Secret Arts',
      selectable: true,
      takes: 2,
      requiresLevel: 2,
      body: 'You have a "Sacred Pouch" (3 Stock, *magical*), as per the Blessed, but with no remarkable traits. Each time you take this move, choose a Blessed move for which you otherwise qualify. (You can\'t take Improved Stat or Superior Stat.)',
    },
    {
      id: 'seeker-lets-make-a-deal',
      name: "Let's Make a Deal",
      selectable: true,
      triggerOverride: 'When you **Seek Insight**, add "What do they really want or need?" to the list of questions. When you **Persuade by offering them something that you know they want or need**, treat a 7-9 as a 10+.',
    },
    {
      id: 'seeker-logbook',
      name: 'Logbook',
      selectable: true,
      uses: 2,
      triggerOverride: 'You have a logbook (2 uses, *slow*) that doesn\'t take up space in your inventory. When you (and only you) **consult your logbook and expend a use**, you can ignore a Know Things roll you just made and treat the result as a 10+. When *the Seasons Change*, reset your logbook to 2 uses.',
    },
    {
      id: 'seeker-magpie',
      name: 'Magpie',
      selectable: true,
      triggerOverride: 'When you **Have What You Need**, you can produce something strange, specific, maybe even valuable or a little bit magical, but if you do, tell us where you got it and 2 of the following:',
      list: [
        "How it's not quite right, but maybe it'll do?",
        'The trouble you caused back home by getting it',
        'Why using it will draw unwanted attention',
        "That it's the only thing like this that you've got, and why it'll only work the one time",
      ],
    },
    {
      id: 'seeker-never-at-a-loss',
      name: 'Never at a Loss',
      selectable: true,
      triggerOverride: "When you **Know Things and roll a 6-**, you may choose to not mark XP. If you don't mark XP, the worst that happens is that the GM tells you nothing interesting or useful about the subject, but instead tells you how you could learn more.",
    },
    {
      id: 'seeker-polyglot',
      name: 'Polyglot',
      selectable: true,
      triggerOverride: 'When you **first encounter a living language in play**, describe your proficiency with it (if any) and how you came to acquire it.',
      body: 'When you **Know Things about any script, text, runes or symbols that you encounter**, you have advantage.',
    },
    {
      id: 'seeker-cryptologist',
      name: 'Cryptologist',
      selectable: true,
      requires: ['seeker-polyglot'],
      triggerOverride: 'When you **study encoded, forgotten, or arcane marks or writing**, roll +INT: **on a 10+**, you can fully decipher them in just a few minutes; **on a 7-9**, you get the gist in a few minutes, but fully deciphering them will take an hour or so.',
    },
    {
      id: 'seeker-quick-study',
      name: 'Quick Study',
      selectable: true,
      triggerOverride: 'When you **study something magical that should take months to understand**, it instead takes mere weeks. If it should take weeks, it takes days. If it should take days, it takes only a few hours.',
    },
    {
      id: 'seeker-safety-first',
      name: 'Safety First',
      selectable: true,
      uses: 2,
      triggerOverride: 'When you **spend an hour or so preparing your mystical defenses**, hold 2 Protection. When you **are affected by harmful magic**, spend 1 Protection either to gain advantage on any roll to resist it or to halve its damage/effects.',
    },
    {
      id: 'seeker-sage-advice',
      name: 'Sage Advice',
      selectable: true,
      triggerOverride: 'When **another PC asks you for guidance**, they get advantage on their next roll to follow your advice.',
    },
    {
      id: 'seeker-arcane-adept',
      name: 'Arcane Adept',
      selectable: true,
      requiresLevel: 6,
      triggerOverride: 'When you **wish to invent a spell or magical effect**, detail its workings with the GM and Make a Plan to invent it. If you like, pick one requirement and ask the GM to provide an alternative (for example "first you must ___" could become "first you must ___, or it will take months").',
    },
    {
      id: 'seeker-deep-insight',
      name: 'Deep Insight',
      selectable: true,
      requiresLevel: 6,
      requires: ['seeker-attuned'],
      triggerOverride: 'When you **Seek Insight about something magical**, you may ask one additional question, not limited to the list. Even on a 6-, you get to ask this question.',
    },
    {
      id: 'seeker-improvise',
      name: 'Improvise',
      selectable: true,
      requiresLevel: 6,
      requires: ['seeker-quick-study'],
      triggerOverride: "When you **wish to use an arcanum's move or option without having unlocked it**, ask the GM what fool risk(s) it requires and/or what consequence(s) you'll incur. If you go for it, roll +INT: **on a 7+**, you get it to work this once — trigger the move or use the option as if you'd unlocked it; and **on a 10+**, also mark one step towards unlocking the arcanum's mysteries.",
    },
    {
      id: 'seeker-superior-stat',
      name: 'Superior Stat',
      selectable: true,
      requiresLevel: 6,
      body: 'Increase one of your stats by +1 (to a max of +3).',
    },
    {
      id: 'seeker-mind-over-magic',
      name: 'Mind Over Magic',
      selectable: true,
      requiresLevel: 6,
      triggerOverride: 'When you **roll to study or use an arcanum**, you can roll +INT instead of the stat you\'d normally roll.',
    },
    {
      id: 'seeker-overchannel',
      name: 'Overchannel',
      selectable: true,
      requiresLevel: 6,
      requires: ['seeker-conduit-of-power'],
      triggerOverride: 'When you **would mark a Consequence from a major arcanum**, you may mark a debility instead.',
    },
    {
      id: 'seeker-proof-against-detection',
      name: 'Proof Against Detection',
      selectable: true,
      requiresLevel: 6,
      requires: ['seeker-safety-first'],
      triggerOverride: "When you **hold Protection**, you can't be scried upon or sensed by magical means, and have advantage to Defy Danger by being stealthy.",
    },
  ],
  ranger: [
    {
      id: 'ranger-a-safe-place',
      name: 'A Safe Place',
      selectable: true,
      uses: 2,
      triggerOverride: 'When you **select and prepare the party\'s camp site**, hold 1 Precaution, or 2 Precaution if you are well-versed with this area and its dangers.',
      body: 'If trouble finds your camp site, you can spend 1 Precaution to reveal a simple defense, warning, or trick that you prepared in advance. If you do, tell us how you knew to make that specific preparation.',
    },
    {
      id: 'ranger-animal-companion',
      name: 'Animal Companion',
      selectable: true,
      triggerOverride: 'You are accompanied by a beast of uncommon loyalty and cleverness. See the Animal Companion insert for details.',
    },
    {
      id: 'ranger-magnificent-specimen',
      name: 'Magnificent Specimen',
      selectable: true,
      takes: 1,
      requiresLevel: 2,
      requires: ['ranger-animal-companion'],
      triggerOverride: 'Each time you take this move, your companion gains 2 additional options of your choice.',
    },
    {
      id: 'ranger-big-game-hunter',
      name: 'Big Game Hunter',
      selectable: true,
      triggerOverride: 'When you **strike at the weak spot of a** ***large*** **or** ***huge*** **creature**, you deal +2 damage.',
    },
    {
      id: 'ranger-blot-out-the-sun',
      name: 'Blot Out the Sun',
      selectable: true,
      triggerOverride: 'When you **Let Fly with a bow**, you can deplete your ammunition (mark the next ammo status after your weapon) before you roll. If you do, choose 1:',
      list: [
        'Gain advantage on your damage roll',
        'Add the *area* tag to your attack; roll damage separately for each target',
      ],
    },
    {
      id: 'ranger-call-the-shot',
      name: 'Call the Shot',
      selectable: true,
      triggerOverride: 'When you **take your time and calmly line up the perfect shot**, either deal your damage or roll +DEX: **on a 10+**, deal your damage and pick 2; **on a 7-9**, deal your damage and pick 1.',
      list: [
        'Ignore armor or deal +1d4 damage (your call)',
        'Stun, hobble, or hinder them',
        'Make them trip or drop what they\'re holding',
        'Do no harm; don\'t deal your damage after all',
      ],
    },
    {
      id: 'ranger-expert-tracker',
      name: 'Expert Tracker',
      selectable: true,
      triggerOverride: 'When you **Seek Insight by searching for or studying the signs left by passing creatures**, you can ask "What happened here recently?" for free, even on a 6-. When you *follow a creature\'s trail*, roll +WIS: **on a 7+** you follow it to a significant change in terrain or activity; **on a 10+**, you can ask the GM a reasonable question about your quarry and get a useful answer.',
    },
    {
      id: 'ranger-home-on-the-range',
      name: 'Home on the Range',
      selectable: true,
      startingMove: true,
      triggerOverride: 'When ***a journey requires you to Defy Danger or Struggle as One***, treat a 6- as a 7-9.',
    },
    {
      id: 'ranger-improved-stat',
      name: 'Improved Stat',
      selectable: true,
      takes: 2,
      triggerOverride: 'Each time you take this move, increase one of your stats by 1 (to a max of +2).',
    },
    {
      id: 'ranger-mental-map',
      name: 'Mental Map',
      selectable: true,
      triggerOverride: 'You can always retrace your steps and can accurately gauge distances and directions. You might not know the way forward but can always find your way back. When you **think back on a place you\'ve been**, you can Seek Insight retroactively, as if you were still there.',
    },
    {
      id: 'ranger-naturalist',
      name: 'Naturalist',
      selectable: true,
      triggerOverride: 'When you **Know Things about beasts, natural environs, or spirits of the wild**, you have advantage.',
    },
    {
      id: 'ranger-on-the-hoof',
      name: 'On the Hoof',
      selectable: true,
      triggerOverride: 'When you **travel through the wilderness**, you can procure 1d6 uses of ◊ provisions each day (roll with disadvantage in winter or barren terrain). Provisions can substitute for supplies when you Make Camp.',
    },
    {
      id: 'ranger-pack-horse',
      name: 'Pack Horse',
      selectable: true,
      triggerOverride: 'You can carry up to 4◈ with a light load, 7◈ with a normal load, and 10◈ with a heavy load.',
    },
    {
      id: 'ranger-pathfinder',
      name: 'Pathfinder',
      selectable: true,
      triggerOverride: 'When you **lead your people to Pull Together or Deploy beyond sight of home**, you have advantage.',
    },
    {
      id: 'ranger-predator',
      name: 'Predator',
      selectable: true,
      triggerOverride: 'When you **Seek Insight**, add the following to the list of questions you can ask. When *acting on the answer to either question*, deal an extra 1d4 damage.',
      list: [
        'Who or what here is the easiest prey?',
        'How is ________ weak or vulnerable?',
      ],
    },
    {
      id: 'ranger-sniff-out-corruption',
      name: 'Sniff Out Corruption',
      selectable: true,
      triggerOverride: 'When you **Seek Insight**, you can ask, "What here stinks of the unnatural?" for free, even on a 6-.',
    },
    {
      id: 'ranger-stalker',
      name: 'Stalker',
      selectable: true,
      triggerOverride: 'When you **carry a normal or light load and move with care**, you make no noise and leave no sign of your passing. When you **hide yourself in a natural environment**, you remain unseen until you draw attention to yourself, move positions, or attack.',
    },
    {
      id: 'ranger-survivalist',
      name: 'Survivalist',
      selectable: true,
      triggerOverride: 'When you **Forage**, pick 1 extra choice (even on a 6-, pick 1) and add "Find or fashion some useful item or supply (GM can veto)" to the list of options.',
    },
    {
      id: 'ranger-warden-of-the-wild',
      name: 'Warden of the Wild',
      selectable: true,
      triggerOverride: 'When you **defeat a perversion of nature**, you can ask the GM 2 of the following and get a useful answer:',
      list: [
        'Will it come back? If so, how can I stop it?',
        'Will its taint spread? If so, how can I contain it?',
        'What useful (but grisly) bits can I harvest?',
        'What else can I learn about it or its ilk?',
      ],
    },
    {
      id: 'ranger-wild-speech',
      name: 'Wild Speech',
      selectable: true,
      triggerOverride: 'The grunts, barks, chirps, and calls of natural beasts are a language to you. You can understand their intentions and communicate basic ideas. When you **Persuade a beast**, you can choose to roll +WIS.',
    },
    {
      id: 'ranger-worldly',
      name: 'Worldly',
      selectable: true,
      takes: 1,
      requiresLevel: 2,
      requires: ['ranger-home-on-the-range'],
      triggerOverride: 'Take a move from the Blessed, Fox, Heavy, Marshal, or Seeker playbooks, for which you otherwise qualify. You can pick from a different playbook each time. You can\'t pick Improved Stat or Superior Stat.',
    },
    {
      id: 'ranger-alpha',
      name: 'Alpha',
      selectable: true,
      requiresLevel: 6,
      requires: ['ranger-animal-companion', 'ranger-wild-speech'],
      triggerOverride: 'When you **assert dominance over another (beast, spirit, Fae, or person)**, roll +WIS: **on a 7+**, they must pick 1 from the list below; **on a 10+**, you also have advantage on your next roll against them.',
      list: [
        'Accept your authority, at least for now',
        'Slink away or flee, then avoid you',
        'Fight you for dominance',
      ],
    },
    {
      id: 'ranger-beast-of-legend',
      name: 'Beast of Legend',
      selectable: true,
      takes: 1,
      requiresLevel: 6,
      requires: ['ranger-magnificent-specimen'],
      triggerOverride: 'Each time you take this move, pick 1:',
      list: [
        'They are *exceptional* (and roll +2 instead of +1)',
        'They get +4 HP and +1 armor',
        'They develop some unique ability or trait',
      ],
    },
    {
      id: 'ranger-constant-vigilance',
      name: 'Constant Vigilance',
      selectable: true,
      requiresLevel: 6,
      triggerOverride: 'Unless you\'re *dazed*, you\'re never caught off guard—not even when asleep or if you roll a 6-. When you **intercept a sudden threat** (to yourself or an ally), you have advantage on whatever move you make.',
    },
    {
      id: 'ranger-giant-slayer',
      name: 'Giant Slayer',
      selectable: true,
      requiresLevel: 6,
      requires: ['ranger-big-game-hunter'],
      triggerOverride: 'When you **strike at a weak spot of a** ***large*** **or** ***huge*** **creature**, you deal another +2 damage (+4 total).',
    },
    {
      id: 'ranger-superior-stat',
      name: 'Superior Stat',
      selectable: true,
      requiresLevel: 6,
      triggerOverride: 'Increase one of your stats by +1 (to a max of +3).',
    },
    {
      id: 'ranger-trailblazer',
      name: 'Trailblazer',
      selectable: true,
      requiresLevel: 6,
      requires: ['ranger-home-on-the-range'],
      triggerOverride: 'When ***a journey causes you to Defy Danger or Struggle as One*** you also learn or discover something interesting and useful—ask the GM what.',
    },
    {
      id: 'ranger-walk-it-off',
      name: 'Walk it Off',
      selectable: true,
      requiresLevel: 6,
      uses: 1,
      triggerOverride: 'When you\'d **mark a debility**, you can mark this move instead to no ill effect. Clear it as you would a debility.',
    },
  ],
};

export const BACKGROUND_FORCED_MOVES: Partial<Record<PlaybookType, Record<string, string[]>>> = {
  blessed: {
    initiate: ['blessed-rites-of-the-land'],
    'raised-by-wolves': ['blessed-trackless-step'],
    vessel: ['blessed-danus-grasp'],
  },
  seeker: {
    patriot: ['seeker-lets-make-a-deal'],
    antiquarian: ['seeker-polyglot'],
    'witch-hunter': ['seeker-everything-bleeds'],
  },
};

// Background grants are computed at render time so they survive background changes without writing to Firestore.
export const BACKGROUND_FORCED_CHECKLIST: Partial<Record<PlaybookType, Record<string, Record<string, string[]>>>> = {
  seeker: {
    patriot: { 'seeker-well-versed': ['sk-wv-things-below'] },
    antiquarian: { 'seeker-well-versed': ['sk-wv-makers'] },
  },
};
