import type { MoveDefinition } from "@/components/CharacterSheet/Move";
import type { PlaybookType } from "@/types";

export const PLAYBOOK_MOVES: Partial<Record<PlaybookType, MoveDefinition[]>> = {
  blessed: [
    {
      id: 'blessed-amulets-and-talismans',
      name: 'Amulets & Talismans',
      selectable: true,
      triggerOverride: 'When you **craft a protective charm for someone**, spend 1 Stock and name a source of harm (fire, stabbing, etc.). When they **would suffer such harm while bearing your charm**, roll +INT: **on a 10+**, they ignore the harm entirely; **on a 7-9**, they suffer only half the damage or effect; **on a 6-**, they suffer the harm normally. One can benefit from only 1 charm at a time, and it loses its potency after 1 use.',
    },
    {
      id: 'blessed-barkskin',
      name: 'Barkskin',
      selectable: true,
      triggerOverride: 'When you **are touching the earth**, you have 2 armor. When you **mark another with 1 Stock**, they gain this benefit so long as the mark remains.',
    },
    {
      id: 'blessed-big-magic',
      name: 'Big Magic',
      selectable: true,
      takes: 2,
      body: 'Each time you take this move, choose an additional remarkable trait for your sacred pouch and increase your max Stock by 2.',
    },
    {
      id: 'blessed-borrow-power',
      name: 'Borrow Power',
      selectable: true,
      requires: ['blessed-spirit-tongue'],
      triggerOverride: 'When **a spirit or beast loans you power**, ask the GM for one of its tags or moves. Store it in your pouch in place of 1 Stock. When you **use the borrowed tag or move**, roll +WIS: **on a 10+**, you do it and can use the power again; **on a 7-9**, you do it, but lose the power.',
    },
    {
      id: 'blessed-call-the-spirits',
      name: 'Call the Spirits',
      selectable: true,
      startingMove: true,
      requires: ['blessed-spirit-tongue'],
      trigger: 'spend 1 Stock and perform a short rite',
      footer: 'the spirit(s) of a place or object manifest and hear you out. What they do next is up to them.',
    },
    {
      id: 'blessed-danus-grasp',
      name: "Danu's Grasp",
      selectable: true,
      triggerOverride: "When you **call on the world itself to bind a spirit or a perversion of nature**, spend 1 Stock and roll +WIS: **on a 7+**, roots, vines, and earth pull at them, and they pick 1; **on a 10+**, as a 7-9, but both apply.",
      list: [
        "They're restrained, unable to act freely until your focus slips or they tear their way free",
        'They take 2d4 damage (ignores armor)',
      ],
      footer: 'If this brings them to 0 HP, they are pulled into the earth and bound in rune-etched stone.',
    },
    {
      id: 'blessed-healers-arts',
      name: "Healer's Arts",
      selectable: true,
      triggerOverride: 'When **someone Recovers under your care**, they recover (extra) HP equal to your WIS. If you **also spend 1 Stock**, they heal an extra 5 HP and their wounds/injuries are stabilized.',
    },
    {
      id: 'blessed-heed-my-words',
      name: 'Heed My Words',
      selectable: true,
      trigger: 'Persuade by talking sense or warning against foolishness',
      triggerOverride: 'When you **Persuade by talking sense or warning against foolishness**, you have advantage.',
    },
    {
      id: 'blessed-improved-stat',
      name: 'Improved Stat',
      selectable: true,
      takes: 2,
      body: 'Each time you take this move, increase one of your stats by 1 (to a max of +2).',
    },
    {
      id: 'blessed-into-the-lions-den',
      name: "Into the Lion's Den",
      selectable: true,
      triggerOverride: 'When you **approach a beast calmly and show no fear**, it will not harm you (though it may threaten you and test your nerve). When you **lay your hand gently upon a beast**, it calms to your touch.',
    },
    {
      id: 'blessed-lightning-rod',
      name: 'Lightning Rod',
      selectable: true,
      triggerOverride: 'When you **Defend while touching the earth**, you can spend 1 Readiness to intercept a nearby magical attack and redirect it harmlessly into the ground.',
    },
    {
      id: 'blessed-natures-wrath',
      name: "Nature's Wrath",
      selectable: true,
      requires: ['blessed-danus-grasp'],
      requiresLevel: 6,
      body: "Danu's Grasp gains the area tag and can affect any creature. A mortal reduced to 0 HP is subdued or killed (your choice) rather than bound in stone.",
    },
    {
      id: 'blessed-potent-workings',
      name: 'Potent Workings',
      selectable: true,
      requires: ['blessed-amulets-and-talismans'],
      requiresLevel: 6,
      triggerOverride: 'When you **craft a protective charm**, you may spend 1 additional Stock to choose 1:',
      list: [
        'Name an additional type of harm',
        'On a 10+, the charm retains its potency',
      ],
    },
    {
      id: 'blessed-rites-of-the-land',
      name: 'Rites of the Land',
      selectable: true,
      uses: 4,
      triggerOverride: 'Once per season, when you **oversee the sacred rites**, hold 1 Favor. If you also sacrifice 1 Surplus, hold 4 Favor instead. Spend Favor in lieu of Stock, 1-for-1.',
      footer: 'When you **publicly sacrifice something or someone much-loved**, either clear a steading debility or gain advantage when the steading next rolls +Fortunes.',
    },
    {
      id: 'blessed-shared-souls',
      name: 'Shared Souls',
      selectable: true,
      requires: ['blessed-into-the-lions-den'],
      requiresLevel: 6,
      triggerOverride: 'When you **mark a beast with 1 Stock**, you can direct its actions and perceive through its senses no matter the distance between you. Treat it as a follower with 3 Loyalty; when you spend its last Loyalty, the effect ends.',
    },
    {
      id: 'blessed-spirit-tongue',
      name: 'Spirit Tongue',
      selectable: true,
      startingMove: true,
      body: 'You can speak with beasts and spirits. You can always ask the GM, "What spirits are active here?" and get an honest answer.',
    },
    {
      id: 'blessed-suck-the-poison-out',
      name: 'Suck the Poison Out',
      selectable: true,
      requires: ['blessed-healers-arts'],
      requiresLevel: 6,
      triggerOverride: "When you **draw a malady from a patient's body, mind, or soul**, spend 1 Stock and roll +WIS: **on a 10+**, you remove the malady and can safely discard it or store it in your sacred pouch (taking the space of 1 Stock) to study or inflict on another; **on a 7-9**, you remove it, but choose 1:",
      list: [
        'Your patient suffers lingering harm or trauma',
        "You suffer some of the malady's effects",
        'It will be harmful and dangerous to discard',
      ],
    },
    {
      id: 'blessed-superior-stat',
      name: 'Superior Stat',
      selectable: true,
      requiresLevel: 6,
      body: 'Increase one of your stats by +1 (to a max of +3).',
    },
    {
      id: 'blessed-trackless-step',
      name: 'Trackless Step',
      selectable: true,
      triggerOverride: 'When you **move through nature with care and patience**, you make no sound, leave no trace and can ignore any hindering or treacherous terrain (briars, mire, scree, etc.). When you **spend 1 Stock and mark others**, they each gain this benefit so long as the mark remains. 1 Stock can mark a number of individuals up to your level +INT.',
    },
    {
      id: 'blessed-veil',
      name: 'Veil',
      selectable: true,
      triggerOverride: 'When you **wrap yourself or another in a subtle veil**, spend 1 Stock and choose 1:',
      list: [
        'A type of being you name (including "people") will tend to ignore your presence',
        "People will perceive you as someone else, though you must wear something of an individual's in order to impersonate them",
      ],
      footer: 'When **your deception comes under scrutiny**, roll +INT: **on a 10+**, the veil holds, and no one is the wiser; **on a 7-9**, the veil holds, but there is further scrutiny or a complication (GM\'s choice).',
    },
    {
      id: 'blessed-voice-of-the-earth-mother',
      name: 'Voice of the Earth Mother',
      selectable: true,
      requires: ['blessed-spirit-tongue'],
      requiresLevel: 6,
      triggerOverride: 'When you **speak on behalf of Danu**, natural beasts and spirits of the wild respect your authority. All but the most headstrong will do as you command, even against their instincts.',
    },
    {
      id: 'blessed-wards-and-bindings',
      name: 'Wards & Bindings',
      selectable: true,
      triggerOverride: 'When you **mark a boundary with sacred signs**, spend 1 Stock and describe who or what they affect (using no more words than your level). Also, choose whether the affected beings are repelled or trapped by the signs.',
      footer: 'When **your wards or bindings are first tested**, roll +INT: **on a 10+**, they will hold as long as the signs remain unmarred (and the affected creature can do nothing to affect them directly); **on a 7-9**, they hold for now but may be overcome through might or will.',
    },
    {
      id: 'blessed-wild-soul',
      name: 'Wild Soul',
      selectable: true,
      requiresLevel: 2,
      body: "Each time you take this move, gain a Ranger move of your choice for which you qualify. You can't pick Improved Stat or Superior Stat.",
    },
  ],
};

export const BACKGROUND_FORCED_MOVES: Partial<Record<PlaybookType, Record<string, string[]>>> = {
  blessed: {
    initiate: ['blessed-rites-of-the-land'],
    'raised-by-wolves': ['blessed-trackless-step'],
    vessel: ['blessed-danus-grasp'],
  },
};
