import type { MoveDefinition } from '@/components/CharacterSheet/Move';
import { IMPROVED_STAT_BASE, SUPERIOR_STAT_BASE } from './_statMoves';

export const HEAVY_MOVES: MoveDefinition[] = [
  {
    id: 'heavy-dangerous',
    name: 'Dangerous',
    selectable: true,
    startingMove: true,
    triggerOverride: 'When you **deal your damage**, you have advantage.',
  },
  {
    id: 'heavy-hard-to-kill',
    name: 'Hard to Kill',
    selectable: true,
    startingMove: true,
    triggerOverride: 'When you **are at Death\'s Door**, you can roll +CON or +nothing (your choice). **On a 7-9**, you can mark a debility of your choice to regain 1 HP.',
  },
  {
    id: 'heavy-armored',
    name: 'Armored',
    selectable: true,
    triggerOverride: 'When you *carry a shield*, mark only ◈ (instead of ◈◈). Also, you can ignore the *cumbersome* tag on any armor you wear.',
    body: 'If you take this move at the start of play, add an ◊◊ iron hauberk, ◊◊ bronze cuirass, or ◊◊ scale coat to your inventory (all are 2 armor, *warm*, *cumbersome*).',
  },
  {
    id: 'heavy-battle-joy',
    name: 'Battle Joy',
    selectable: true,
    requiresLevel: 2,
    triggerOverride: 'When you ***spill blood—yours or another\'s—and lose yourself in battle***, you ignore fear, pain, mind-control, and the effects of debilities as long as you keep fighting.',
    footer: 'When *the action stops*, roll +CON: **on a 10+**, that was a rush, regain 1d4 HP; **on a 7-9**, you\'re winded and out of it, but you\'ll be fine with a few minutes\' rest; **on a 6-**, mark a debility but don\'t mark XP.',
  },
  {
    id: 'heavy-berserker',
    name: 'Berserker',
    selectable: true,
    requiresLevel: 2,
    requires: ['heavy-battle-joy'],
    triggerOverride: 'While ***in your Battle Joy***, add the *area* tag to your melee attacks, lashing out at anyone nearby (friend and foe alike). Roll damage separately for each target.',
  },
  {
    id: 'heavy-carved-out-of-wood',
    name: 'Carved Out of Wood',
    selectable: true,
    requiresLevel: 2,
    body: 'Increase your max HP by 4.',
  },
  {
    id: 'heavy-formidable',
    name: 'Formidable',
    selectable: true,
    requiresLevel: 2,
    triggerOverride: 'When you ***wade into battle***, you can choose to roll +CHA: **on a 10+**, both; **on a 7-9**, pick 1:',
    list: [
      'Lesser foes will quail, hesitate, or flee before you.',
      'Doughty foes will focus on you, seeing you as the greatest threat.',
    ],
    footer: '**On a 6-**, pick 1 but ask the GM what you\'ve missed.',
  },
  {
    id: 'heavy-frosty',
    name: 'Frosty',
    selectable: true,
    requiresLevel: 2,
    triggerOverride: 'When you **Defy Danger by keeping calm and carrying on**, **on a 10+** you can also ask the GM a question that you could ask when Seeking Insight. You have advantage on your next move to act on the answer.',
  },
  {
    id: 'heavy-guardian',
    name: 'Guardian',
    selectable: true,
    requiresLevel: 2,
    triggerOverride: 'When you **Defend**, hold 1 extra Readiness. Even on a 6-, hold 1 Readiness (plus whatever the GM says).',
  },
  { ...IMPROVED_STAT_BASE, id: 'heavy-improved-stat', requiresLevel: 2 },
  {
    id: 'heavy-intimidating',
    name: 'Intimidating',
    selectable: true,
    requiresLevel: 2,
    triggerOverride: 'When you **Persuade using violence or threats**, you have advantage.',
  },
  {
    id: 'heavy-musclebound',
    name: 'Musclebound',
    selectable: true,
    requiresLevel: 2,
    triggerOverride: 'When you ***make a hand-to-hand or thrown attack***, it\'s *forceful* and *messy*. If it would already be *forceful* and/or *messy*, it\'s even more so.',
    body: '(Requires Strength +2 or higher)',
  },
  {
    id: 'heavy-payback',
    name: 'Payback',
    selectable: true,
    requiresLevel: 2,
    triggerOverride: 'When you **deal damage to a foe that has harmed you or one of your allies**, deal +1d4 damage.',
  },
  {
    id: 'heavy-relentless',
    name: 'Relentless',
    selectable: true,
    requiresLevel: 2,
    triggerOverride: 'When you **Clash and your foe survives**, you gain advantage the next time you Clash with them.',
  },
  {
    id: 'heavy-seasoned-warrior',
    name: 'Seasoned Warrior',
    selectable: true,
    takes: 2,
    requiresLevel: 2,
    body: 'Take a move from the Fox, Marshal, Ranger, or Seeker playbooks, for which you otherwise qualify. You can pick from a different playbook each time. (You can\'t pick Improved Stat or Superior Stat.)',
  },
  {
    id: 'heavy-situational-awareness',
    name: 'Situational Awareness',
    selectable: true,
    requiresLevel: 2,
    triggerOverride: 'When you **Seek Insight**, add the following to the list of questions you can ask:',
    list: [
      'Who or what here is the biggest threat?',
      'What is my enemy\'s true position?',
      'What here can I use as a weapon?',
    ],
    footer: 'When *a fight breaks out*, ask the GM 1 question that you could ask when Seeking Insight.',
  },
  {
    id: 'heavy-uncanny-reflexes',
    name: 'Uncanny Reflexes',
    selectable: true,
    triggerOverride: 'When you ***are unarmored and carrying a normal or light load***, you impose disadvantage on any damage you take that you could dodge or roll with.',
  },
  {
    id: 'heavy-unfettered',
    name: 'Unfettered',
    selectable: true,
    requiresLevel: 2,
    triggerOverride: 'When you ***are subject to physical or mental restraint***, you may mark a debility to immediately break free of that restraint.',
  },
  {
    id: 'heavy-unstoppable',
    name: 'Unstoppable',
    selectable: true,
    requiresLevel: 2,
    uses: 5,
    requires: ['heavy-hard-to-kill'],
    triggerOverride: 'When you ***are reduced to 0 HP in battle***, you can keep fighting. Each time you take damage while at 0 HP, mark 1. If you would regain HP while fighting, clear one mark instead.',
    footer: 'When you ***stop fighting***, roll for Death\'s Door with a -1 penalty for each circle marked. If you survive, clear all your circles.',
  },
  {
    id: 'heavy-terror-on-the-field',
    name: 'Terror on the Field',
    selectable: true,
    requiresLevel: 2,
    triggerOverride: 'When you ***reduce a foe to 0 HP***, describe how you take them out. If you fell them in a particularly brutal or impressive manner, their allies are impressed, dismayed, or frightened and respond accordingly.',
  },
  {
    id: 'heavy-bringer-of-ruin',
    name: 'Bringer of Ruin',
    selectable: true,
    requiresLevel: 6,
    triggerOverride: 'When you ***roll a 12+ to Clash and your foe survives***, name something they possess (like their sword, their position, a limb, their dignity, etc.), but nothing that would kill them outright. Whatever you name, it is broken, shattered, lost. Tell us how.',
  },
  {
    id: 'heavy-cut-from-granite',
    name: 'Cut from Granite',
    selectable: true,
    requiresLevel: 6,
    requires: ['heavy-carved-out-of-wood'],
    body: 'Gain +1 armor (stacks with other sources) and increase your max HP by another 2 (+6 HP total).',
  },
  {
    id: 'heavy-mighty-thews',
    name: 'Mighty Thews',
    selectable: true,
    requiresLevel: 6,
    requires: ['heavy-musclebound'],
    triggerOverride: 'When you ***perform a feat of extraordinary strength*** (bursting chains, smashing through a wall, heaving a boulder, etc.), you do it (OH YEAH!) but pick 1:',
    list: [
      'It takes a while',
      'You cause unwanted damage or harm',
      'It takes a toll (mark a debility)',
    ],
  },
  {
    id: 'heavy-nemesis',
    name: 'Nemesis',
    selectable: true,
    requiresLevel: 6,
    requires: ['heavy-relentless'],
    triggerOverride: 'When you **Clash and your foe survives**, all of your future attacks against them do +1d6 damage.',
  },
  {
    id: 'heavy-steadfast-guardian',
    name: 'Steadfast Guardian',
    selectable: true,
    requiresLevel: 6,
    requires: ['heavy-guardian'],
    triggerOverride: 'While you ***hold Readiness (from Defend)***, you can always suffer the damage/effects of an attack instead of your ward; no need to spend Readiness, you can just do it.',
  },
  {
    id: 'heavy-stone-cold',
    name: 'Stone Cold',
    selectable: true,
    requiresLevel: 6,
    requires: ['heavy-frosty'],
    triggerOverride: 'When you **Defy Danger (or Struggle as One) by keeping calm and carrying on**, treat a 6- as a 7-9.',
  },
  { ...SUPERIOR_STAT_BASE, id: 'heavy-superior-stat' },
];
