import type { MoveDefinition } from '@/types';
import { IMPROVED_STAT_BASE, SUPERIOR_STAT_BASE } from './_statMoves';

export const JUDGE_MOVES: MoveDefinition[] = [
  {
    id: 'judge-aegis-of-faith',
    name: 'Aegis of Faith',
    selectable: true,
    triggerOverride: 'When you **wield a shield**, it can turn away spells, magical effects, and insubstantial attacks as if they were physical blows.',
  },
  {
    id: 'judge-armored',
    name: 'Armored',
    selectable: true,
    triggerOverride: 'When you **carry a shield**, mark only ◈ (instead of ◈◈). Also, you can ignore the *cumbersome* tag on any armor you wear.',
    footer: 'If you take this move at the start of play, add an ◊◊ iron hauberk, ◊◊ bronze cuirass, or ◊◊ scale coat to your inventory (all are 2 armor, *warm, cumbersome*).',
  },
  {
    id: 'judge-bear-witness',
    name: 'Bear Witness',
    selectable: true,
    triggerOverride: 'When you **speak the truth with conviction and candor**, none can doubt you. They might deny what you say, but in their hearts they recognize the truth.',
  },
  {
    id: 'judge-break-bread',
    name: 'Break Bread',
    selectable: true,
    triggerOverride: 'When you **share a proper meal with someone and each of you eats their fill**, each of you recovers 1d8 (extra) HP.',
  },
  {
    id: 'judge-bulwark',
    name: 'Bulwark',
    selectable: true,
    triggerOverride: 'When you **Defend**, you can spend 1 Readiness to stand fast, holding your position despite what befalls you.',
  },
  {
    id: 'judge-censure',
    name: 'Censure',
    selectable: true,
    startingMove: true,
    triggerOverride: 'When you **first denounce an individual in your presence as an agent of chaos or anathema to civilization**, they pick 1:',
    list: [
      'They are ashamed, and act accordingly',
      'They are doubtful, and hesitate, pause',
      'They are afraid, and seek to escape',
      'They are enraged, and lash out predictably (the next roll against them has advantage)',
    ],
  },
  {
    id: 'judge-castigate',
    name: 'Castigate',
    selectable: true,
    requiresLevel: 2,
    requires: ['judge-censure'],
    triggerOverride: 'When you **Censure someone**, your voice deals 1d4 damage to them (*near*, *loud*, ignores armor).',
  },
  {
    id: 'judge-chronicler-of-stonetop',
    name: 'Chronicler of Stonetop',
    selectable: true,
    startingMove: true,
    uses: 3,
    triggerOverride: 'When you **write up detailed session notes and share them with the other players**, hold +1 Diligence.',
    body: 'You can spend 1 Diligence at any time to add +1 to a roll that you or a fellow player just made.',
  },
  {
    id: 'judge-for-the-greater-good',
    name: 'For the Greater Good',
    selectable: true,
    triggerOverride: 'When you **Persuade someone to act in defense of their community or civilization at large**, you have advantage.',
  },
  {
    id: 'judge-hound-of-aratis',
    name: 'Hound of Aratis',
    selectable: true,
    triggerOverride: 'When you **Seek Insight**, you can always ask "What here is tainted by chaos?" for free, even on a 6-.',
  },
  {
    id: 'judge-like-a-dog-with-a-bone',
    name: 'Like a Dog With a Bone',
    selectable: true,
    requires: ['judge-hound-of-aratis'],
    triggerOverride: 'When you **attack something you know to be tainted by chaos**, deal +1d6 damage.',
  },
  { ...IMPROVED_STAT_BASE, id: 'judge-improved-stat' },
  {
    id: 'judge-knowledge-is-power',
    name: 'Knowledge is Power',
    selectable: true,
    triggerOverride: 'When you **roll 10+ to Know Things**, you or an ally gain advantage on the next roll to act on what you learn.',
  },
  {
    id: 'judge-many-hands-make-light-work',
    name: 'Many Hands Make Light Work',
    selectable: true,
    triggerOverride: 'When you **jump in to help another character who just rolled**, tell us how and ask the GM what else is required or what the consequences will be. If you accept, increase your ally\'s roll by +1.',
  },
  {
    id: 'judge-a-bundle-of-sticks-unbroken',
    name: 'A Bundle of Sticks Unbroken',
    selectable: true,
    requires: ['judge-many-hands-make-light-work'],
    triggerOverride: 'When you Struggle as One, you and one ally of your choice have advantage.',
  },
  {
    id: 'judge-the-hammer-and-the-book',
    name: 'The Hammer and the Book',
    selectable: true,
    triggerOverride: 'When you **strike a thing of supernatural chaos**, roll +WIS: **on a 10+**, deal your damage and choose 1 from the list below; **on a 7-9**, deal your damage and choose 1, but you also expose yourself to harm or unwanted attention.',
    list: [
      'Deal +1d6 damage',
      "Ignore the thing's armor or other defenses",
      'Suppress one of its unnatural powers',
      'Force it from its host',
    ],
  },
  {
    id: 'judge-truth-or-consequences',
    name: 'Truth or Consequences',
    selectable: true,
    triggerOverride: 'When you **look into someone\'s eyes and gaze upon their soul**, you can ask their player, "Are you lying or hiding something from me?" and get an honest answer. If the answer is "Yes," you have advantage on your next roll against them.',
    footer: 'When you **lie or otherwise deceive someone through words**, you have disadvantage on your next roll against them.',
  },
  {
    id: 'judge-binding-arbitration',
    name: 'Binding Arbitration',
    selectable: true,
    requires: ['judge-truth-or-consequences'],
    triggerOverride: 'When you **bear witness to someone\'s promise or oath**, henceforth you may ask their player if they have kept their word. They must answer honestly. The character need not be present. If **they have broken their word**, you gain advantage on all rolls against them until they admit their wrong and suffer an appropriate consequence (your call).',
  },
  {
    id: 'judge-vision-unclouded',
    name: 'Vision Unclouded',
    selectable: true,
    triggerOverride: 'When you **Seek Insight**, you can always ask "What here is hidden by illusion or magic?" for free, even on a 6-.',
  },
  {
    id: 'judge-well-read',
    name: 'Well-Read',
    selectable: true,
    triggerOverride: 'When you **name the source in which you read about the matter at hand**, roll +WIS to Know Things instead of +INT.',
  },
  {
    id: 'judge-a-mighty-rampart',
    name: 'A Mighty Rampart',
    selectable: true,
    requiresLevel: 6,
    requires: ['judge-bulwark'],
    triggerOverride: 'When you **hold Readiness** (from Defend), you cannot be forced from your position. Also, you can spend 1 Readiness to completely ignore the effects/damage of an attack that you suffer.',
  },
  {
    id: 'judge-armistice',
    name: 'Armistice',
    selectable: true,
    requiresLevel: 6,
    requires: ['judge-bear-witness'],
    triggerOverride: 'When you **approach an enemy to negotiate in good faith**, they will at least hear you out. Even the most debased and savage foe will delay violence until you\'ve had your say.',
  },
  {
    id: 'judge-condemn',
    name: 'Condemn',
    selectable: true,
    requiresLevel: 6,
    requires: ['judge-censure'],
    triggerOverride: 'When you **Censure someone**, they are marked with a mystical brand that cannot be removed or hidden until you dismiss it. Any intelligent creature who sees the mark recognizes the bearer as an agent of chaos and anathema to civilization.',
  },
  {
    id: 'judge-proclamation',
    name: 'Proclamation',
    selectable: true,
    requiresLevel: 6,
    requires: ['judge-condemn'],
    triggerOverride: 'When you **Censure**, you may denounce a group or faction as long as you can clearly identify them. Apply the effects of Censure to every member of that group, regardless of distance.',
  },
  {
    id: 'judge-mirrorshield',
    name: 'Mirrorshield',
    selectable: true,
    requiresLevel: 6,
    requires: ['judge-aegis-of-faith'],
    triggerOverride: 'When you **Defend with a shield**, you can spend 1 Readiness to intercept a magical force and redirect it to a different target (or none).',
  },
  { ...SUPERIOR_STAT_BASE, id: 'judge-superior-stat' },
  {
    id: 'judge-the-tower-eternal',
    name: 'The Tower Eternal',
    selectable: true,
    requiresLevel: 6,
    triggerOverride: 'When you **Defy Danger against magic**, treat a result of 6- as a 7-9.',
  },
];
