import type { MoveDefinition } from '@/components/CharacterSheet/Move';
import { IMPROVED_STAT_BASE, SUPERIOR_STAT_BASE } from './_statMoves';

export const LIGHTBEARER_MOVES: MoveDefinition[] = [
  {
    id: 'lb-a-candle-against-the-dark',
    name: 'A Candle Against the Dark',
    selectable: true,
    triggerOverride: 'When you **wield a holy light but go otherwise unarmed**, you have 2 Armor.',
  },
  {
    id: 'lb-luminous-shield',
    name: 'Luminous Shield',
    selectable: true,
    requires: ['lb-a-candle-against-the-dark'],
    triggerOverride: 'When you **brandish a holy light to turn aside an attack against body, mind, or soul**, roll +CHA: **on a 10+**, the attack is deflected and, if the attacker is in range of your light, they are briefly blinded; **on a 7-9**, the attack is deflected but your holy light flickers and dims, threatening to go out; **on a 6-**, your light snuffs out and the attack is unimpeded.',
  },
  {
    id: 'lb-all-is-illuminated',
    name: 'All is Illuminated',
    selectable: true,
    triggerOverride: 'When you **look closely on another and see their soul laid bare**, roll +WIS: **on a 10+**, ask their player 1 question from the list below, plus "And what would make them feel loved, beautiful, or worthy?"; **on a 7-9**, ask them 1 question from the list. In any case, they must answer truthfully.',
    list: [
      'Of what are they most ashamed?',
      'What do they most desire or covet?',
      'What hope have they abandoned?',
      'Who or what is most precious to them?',
    ],
  },
  {
    id: 'lb-and-behold-a-pale-horse',
    name: 'And Behold a Pale Horse',
    selectable: true,
    triggerOverride: 'When you **spend the night gazing into a flame**, ask the GM to reveal an impending doom or grim portent that will come to pass unless you intervene, and how you might yet do so.',
  },
  {
    id: 'lb-consecrated-flame',
    name: 'Consecrated Flame',
    selectable: true,
    startingMove: true,
    triggerOverride: 'When you **whisper words of consecration to a flame**, the flame casts a holy light. Holy light is uncomfortable for creatures of darkness to look upon, but does no true harm. The holy light lasts until the flame goes out or until you consecrate another flame, whichever comes first.',
  },
  {
    id: 'lb-fire-within',
    name: 'Fire Within',
    selectable: true,
    triggerOverride: 'When you **are in darkness**, you are able to see by the light of your inner fire. When you **take damage from cold or fire**, reduce that damage by 2.',
  },
  {
    id: 'lb-guiding-light',
    name: 'Guiding Light',
    selectable: true,
    triggerOverride: 'When you **lead one or more NPCs through danger**, roll +CHA: **on a 10+**, you all make it through (Helior be praised); **on a 7-9**, the GM will tell you what\'s required to get everyone through safely.',
  },
  {
    id: 'lb-heliors-unblinking-eye',
    name: "Helior's Unblinking Eye",
    selectable: true,
    triggerOverride: 'When you **stare into the sun long enough to lose your vision**, name a person or place that you know and roll +WIS: **on a 10+**, you briefly glimpse your subject as if from a great height, and choose 2 from the list below; **on a 7-9**, you briefly glimpse your subject as if from a great height, and choose 1:',
    list: [
      'The glimpse lasts as long as you wish',
      'Your point of view shifts to very close range',
      'You recover your vision quickly',
    ],
  },
  { ...IMPROVED_STAT_BASE, id: 'lb-improved-stat' },
  {
    id: 'lb-invoke-the-sun-god',
    name: 'Invoke the Sun God',
    selectable: true,
    startingMove: true,
    triggerOverride: 'When you **imbue a holy light with Helior\'s power**, choose an Invocation you know and roll +WIS: **on a 10+**, it works as described but you must choose 1 consequence from the list below; **on a 7-9**, it works as described, but you and the GM each choose 1.',
    list: [
      'The Invocation has its *reduced* effect',
      'The effort taxes you; mark a debility',
      'The light is snuffed out when the Invocation is complete, its fuel consumed',
      'You must bask in sunlight for an hour or so before using that Invocation again',
    ],
    footer: 'See the **Invocations** insert for details.',
  },
  {
    id: 'lb-keep-the-home-fires-burning',
    name: 'Keep the Home-Fires Burning',
    selectable: true,
    triggerOverride: 'When you **build a camp fire and sprinkle it with ash from your own hearth**, anyone who Makes Camp with you is free from nightmares or bad dreams and recovers (extra) HP equal to your CHA.',
  },
  {
    id: 'lb-lamplighter',
    name: 'Lamplighter',
    selectable: true,
    triggerOverride: 'When you **whisper to a flammable object** (a torch, a wick, kindling, etc.), it ignites in moments.',
  },
  {
    id: 'lb-piety',
    name: 'Piety',
    selectable: true,
    uses: 1,
    triggerOverride: 'When you **spend at least an hour in proper worship to Helior**, hold 1 Blessing. Other faithful PCs who partake in this worship also hold 1 Blessing. At any time, you can spend 1 Blessing to add +1 to a roll you just made in pursuit of a righteous cause.',
  },
  {
    id: 'lb-purifying-flames',
    name: 'Purifying Flames',
    selectable: true,
    triggerOverride: 'When you **wield a holy light against a creature of darkness**, it counts as a weapon (d10 damage, *hand*, *close*, *area*, 2 piercing) and you can choose to roll +WIS to Clash.',
  },
  {
    id: 'lb-radiant-countenance',
    name: 'Radiant Countenance',
    selectable: true,
    triggerOverride: 'When you **give someone your fond attention**, you can then Persuade them with advantage. If they are a follower, you can instead choose to Strengthen Your Bond (as if you paid their cost).',
  },
  {
    id: 'lb-rise-like-the-sun',
    name: 'Rise Like the Sun',
    selectable: true,
    triggerOverride: 'When you **draw attention to yourself by word or deed**, roll +CHA: **on a 10+**, everyone turns and looks, and you hold their gaze as long as you keep giving them reason to look; **on a 7-9**, everyone turns and looks.',
  },
  {
    id: 'lb-springs-first-thaw',
    name: "Spring's First Thaw",
    selectable: true,
    triggerOverride: 'When you **spend time (an hour at least, maybe more) seeking to stir hope, kindness, or mercy in an NPC**, roll +CHA: **on a 10+**, you light a fire deep within them and effect a lasting change; **on a 7-9**, you kindle goodness in their heart for now, but they will eventually return to their old ways; **on a 6-**, their heart hardens and, whatever else the GM says, you can\'t use this move on them again.',
  },
  {
    id: 'lb-burn-twice-as-bright',
    name: 'Burn Twice as Bright',
    selectable: true,
    requiresLevel: 6,
    requires: ['lb-invoke-the-sun-god'],
    triggerOverride: 'When you **Invoke the Sun God**, you may mark a debility to use 2 Invocations at once. Roll once, and apply any consequences to both Invocations.',
  },
  {
    id: 'lb-empowered-invocations',
    name: 'Empowered Invocations',
    selectable: true,
    requiresLevel: 6,
    requires: ['lb-invoke-the-sun-god'],
    triggerOverride: 'When you Invoke the Sun God, you can choose an extra consequence before you roll. If you do, the Invocation has its *empowered* effect.',
  },
  {
    id: 'lb-glorious-servant',
    name: 'Glorious Servant',
    selectable: true,
    requiresLevel: 6,
    requires: ['lb-invoke-the-sun-god'],
    triggerOverride: 'When you **Invoke the Sun God and roll a 10+**, you need not choose a consequence; **on a 7-9**, you choose a consequence but the GM does not.',
  },
  {
    id: 'lb-hungry-flames',
    name: 'Hungry Flames',
    selectable: true,
    requiresLevel: 6,
    requires: ['lb-purifying-flames'],
    triggerOverride: 'When you **deal damage with a holy light**, you deal +1d6 damage and your target is engulfed in holy light and flames.',
  },
  {
    id: 'lb-light-more-light',
    name: 'Light, More Light',
    selectable: true,
    requiresLevel: 6,
    requires: ['lb-consecrated-flame'],
    triggerOverride: 'When you **consecrate a flame**, it burns brighter than normal. A rushlight or candle illuminates to *reach* range, an oil lamp, lantern, or torch out to *near* range, and a bullseye lantern out to *far* range.',
  },
  { ...SUPERIOR_STAT_BASE, id: 'lb-superior-stat' },
  {
    id: 'lb-wielder-of-the-white-flame',
    name: 'Wielder of the White Flame',
    selectable: true,
    requiresLevel: 6,
    requires: ['lb-invoke-the-sun-god'],
    triggerOverride: 'When you **channel Helior\'s essence into an object you carry**, roll +WIS: **on a 10+**, it ignites with a white flame that casts a holy light (*reach*, *area*) and burns neither you nor the object, and you may Invoke the Sun God right now as if you rolled a 10+; **on a 7-9**, it ignites with a white flame that casts a holy light (*reach*, *area*) and burns neither you nor the object.',
  },
];
