import type { MoveDefinition } from '@/types';
import { IMPROVED_STAT_BASE, SUPERIOR_STAT_BASE } from './_statMoves';

export const MARSHAL_MOVES: MoveDefinition[] = [
  {
    id: 'marshal-armored',
    name: 'Armored',
    selectable: true,
    triggerOverride: 'When you **carry a shield**, mark only ◈ (instead of ◈◈). Also, you can ignore the *cumbersome* tag on any armor you wear.',
    footer: 'If you take this move at the start of play, add an ◊◊ iron hauberk, ◊◊ bronze cuirass, or ◊◊ scale coat to your inventory (all are 2 armor, *warm, cumbersome*).',
  },
  {
    id: 'marshal-arts-of-war',
    name: 'Arts of War',
    selectable: true,
    takes: 1,
    requiresLevel: 2,
    body: 'Take a move from the Fox, Heavy, Judge, Ranger, or Seeker playbooks, for which you otherwise qualify. You can pick from a different playbook each time. You can\'t take Improved Stat or Superior Stat.',
  },
  {
    id: 'marshal-crew',
    name: 'Crew',
    selectable: true,
    startingMove: true,
    body: 'You\'ve got a crew of stalwarts, six or so residents of Stonetop with some steel to them. See the Crew insert for details.',
  },
  {
    id: 'marshal-veteran-crew',
    name: 'Veteran Crew',
    selectable: true,
    takes: 1,
    requires: ['marshal-crew'],
    body: 'Each time you take this move, pick 1. You can also choose to reselect their Instinct and Cost.',
    checkList: [
      'Select 2 new tags for your Crew',
      'Increase their damage die from d6 to d8',
      'Increase their max HP by 2 each',
    ],
    checkListIds: ['marshal-vc-tags', 'marshal-vc-damage', 'marshal-vc-hp'],
  },
  {
    id: 'marshal-front-line-leader',
    name: 'Front Line Leader',
    selectable: true,
    uses: 2,
    triggerOverride: 'When you **lead your crew into battle**, hold 2 Presence. Spend Presence in lieu of your crew\'s Loyalty or as Readiness (as if you Defended them).',
  },
  { ...IMPROVED_STAT_BASE, id: 'marshal-improved-stat' },
  {
    id: 'marshal-logistics',
    name: 'Logistics',
    selectable: true,
    startingMove: true,
    triggerOverride: 'When you **have a steading Muster or Pull Together**, or when you **Requisition**, you have advantage.',
  },
  {
    id: 'marshal-read-the-land',
    name: 'Read the Land',
    selectable: true,
    triggerOverride: 'When you **first take a moment to survey the terrain**, ask the GM one of the following; gain advantage on your next roll to act on the answer.',
    list: [
      'What\'s the best way in, out, through, or past?',
      'Where\'s the best spot for a trap or an ambush?',
      'Where\'s the most defensible position?',
      'What here is out of place?',
    ],
  },
  {
    id: 'marshal-prepare-a-welcome',
    name: 'Prepare a Welcome',
    selectable: true,
    uses: 2,
    requires: ['marshal-read-the-land'],
    triggerOverride: 'When you **have your allies fortify a position and lie in wait for battle**, hold 1 Surprise if you\'re rushed or 2 Surprises if you can take your time.',
    footer: 'Once battle is joined, spend 1 Surprise to reveal a ploy, defense, or dirty trick you prepared in advance and roll +INT: **on a 10+**, it works as well as can be expected, and you\'ve still got a few tricks up your sleeve—regain 1 Surprise; **on a 7-9**, it works as well as can be expected.',
  },
  {
    id: 'marshal-set-up-strike',
    name: 'Set-Up Strike',
    selectable: true,
    triggerOverride: 'When you **Clash and get a 7+**, you can choose to deal damage with disadvantage. If you do, you create an opening for an ally to act on, as if you provided Aid. Describe it!',
  },
  {
    id: 'marshal-shake-it-off',
    name: 'Shake It Off',
    selectable: true,
    triggerOverride: 'When you **order an ally to overcome fear, pain, doubt, or delusion**, roll +CHA: **on a 10+**, they do it; **on a 7-9**, a PC gets advantage on their next roll to do it; an NPC will do it, but they\'ll need time, they\'ll resent you, or they\'ll feel humiliated (GM decides).',
  },
  {
    id: 'marshal-shield-wall',
    name: 'Shield Wall',
    selectable: true,
    triggerOverride: 'When you **have your crew form a shield wall**, they Defend with advantage and **on a 7+** they hold +2 Readiness (instead of the usual +1 for shields). *As long as they maintain formation*, they can go on the offensive without losing Readiness.',
  },
  {
    id: 'marshal-sir-permission-to-die-sir',
    name: 'Sir, Permission to Die, Sir',
    selectable: true,
    triggerOverride: 'When **one of your followers would die**, you can spend 1 of their Loyalty to have them survive (out of the action, but alive). If you let them go, mark XP.',
  },
  {
    id: 'marshal-speak-softly',
    name: 'Speak Softly',
    selectable: true,
    triggerOverride: 'When you **offer peace but your enemy refuses**, gain advantage on your next roll against them.',
  },
  {
    id: 'marshal-stentorian',
    name: 'Stentorian',
    selectable: true,
    uses: 2,
    triggerOverride: 'When you **raise your voice**, it carries far and cuts through even the din of battle. When you **go into battle**, hold 2 Command. Spend 1 Command to shout an order or warning and pick 1:',
    list: [
      'PCs get advantage on their next roll to do as you say',
      'You have advantage to Order Followers or Deploy',
    ],
  },
  {
    id: 'marshal-take-the-measure',
    name: 'Take the Measure',
    selectable: true,
    triggerOverride: 'When you **size someone up**, ask their player one of the questions below and get an honest answer. If they *fear or respect you* (their call), you can ask another question. You can\'t use this move on them again until your relationship significantly changes.',
    list: [
      'Can I trust them (to _____)?',
      'What do they intend to do?',
      'How are they most useful/dangerous?',
      'What weakness of theirs can I exploit?',
    ],
  },
  {
    id: 'marshal-we-happy-few',
    name: 'We Happy Few',
    selectable: true,
    triggerOverride: 'When you **give an inspiring speech to your allies before facing a dire threat**, roll +CHA: **on a 10+**, each ally holds 2 Inspiration; **on a 7-9**, each ally holds 1 Inspiration; **on a 6-**, each ally holds 1, but you have disadvantage on all rolls until you share your nagging doubts with someone else.',
    footer: 'Once battle is joined, your allies can spend their Inspiration at any time, 1-for-1 to do the following:',
    list2: [
      'Act fearlessly in the face of terror or overwhelming odds',
      'Keep 1 HP instead of being reduced to 0 HP',
      'Add 1d6 to a damage roll they just made',
    ],
  },
  {
    id: 'marshal-battlefield-grace',
    name: 'Battlefield Grace',
    selectable: true,
    requiresLevel: 6,
    requires: ['marshal-front-line-leader'],
    triggerOverride: 'When you **take damage while leading your allies in battle**, the damage roll has disadvantage.',
  },
  {
    id: 'marshal-heroes-to-the-last',
    name: 'Heroes to the Last',
    selectable: true,
    takes: 1,
    requiresLevel: 6,
    requires: ['marshal-veteran-crew'],
    body: 'Each time you take this move, pick 1:',
    checkList: [
      'They are *exceptional* (and roll +2 instead of +1)',
      'They are inured to terror & horror',
      'Increase their max HP by 4 each',
      'Increase their damage die one size (max d10)',
    ],
    checkListIds: ['marshal-httl-exceptional', 'marshal-httl-terror', 'marshal-httl-hp', 'marshal-httl-damage'],
  },
  {
    id: 'marshal-focus-fire',
    name: 'Focus Fire',
    selectable: true,
    requiresLevel: 6,
    requires: ['marshal-stentorian'],
    body: 'You can spend 1 Command to order your allies to bring down a foe. If you do, each ally has advantage on their next damage roll against that foe.',
  },
  {
    id: 'marshal-like-an-open-book',
    name: 'Like an Open Book',
    selectable: true,
    requiresLevel: 6,
    requires: ['marshal-take-the-measure'],
    triggerOverride: 'When you **Take the Measure of someone who fears or respects you**, your second question can be anything you want. The GM might ask how you could possibly know this; tell them or ask something else.',
  },
  {
    id: 'marshal-noble-mien',
    name: 'Noble Mien',
    selectable: true,
    requiresLevel: 6,
    triggerOverride: 'When you **lead an NPC through danger and return them to safety**, if they aren\'t part of your crew they will either offer to join your crew or pledge their future aid and support.',
  },
  {
    id: 'marshal-peace-through-strength',
    name: 'Peace Through Strength',
    selectable: true,
    requiresLevel: 6,
    requires: ['marshal-speak-softly'],
    triggerOverride: 'When you **stand ready to fight alongside like-minded allies**, anything capable of fear recognizes you as a serious threat and treats you accordingly.',
  },
  { ...SUPERIOR_STAT_BASE, id: 'marshal-superior-stat' },
];
