import type { MoveDefinition } from '@/components/CharacterSheet/Move';
import { IMPROVED_STAT_BASE, SUPERIOR_STAT_BASE } from './_statMoves';

export const SEEKER_MOVES: MoveDefinition[] = [
  {
    id: 'seeker-well-versed',
    name: 'Well Versed',
    selectable: true,
    startingMove: true,
    takes: 2,
    body: 'Mark 1 topic, in addition to the one noted in your Background. Each additional time you take this move, mark 2 more topics.',
    checkList: [
      'The Last Door, death, and the undead',
      'The civilizations of humanity',
      'The Fae and their strange ways',
      'The Makers and their arts',
      'The primordial powers',
      'The Things Below',
      'The wild world and its spirits',
    ],
    checkListIds: [
      'sk-wv-last-door',
      'sk-wv-civilizations',
      'sk-wv-fae',
      'sk-wv-makers',
      'sk-wv-primordial',
      'sk-wv-things-below',
      'sk-wv-wild-world',
    ],
    footer: 'When you **Know Things about one of your topics**, you can ask the GM a follow-up question of your choice (even on a 6-).',
  },
  {
    id: 'seeker-work-with-what-youve-got',
    name: "Work With What You've Got",
    selectable: true,
    startingMove: true,
    triggerOverride: 'When you **cleverly use your environment to harm or impede your foe(s)**, roll +INT: **on a 10+**, pick 2; **on a 7-9**, pick 1:',
    list: [
      'Interrupt or thwart their action(s)',
      'Create an opportunity that grants you or an ally advantage on the next roll to exploit it',
      "Deal damage appropriate to the source (d4 for bruises/scrapes, d6 for bloodshed, d8 if it'd break bones, d10 if it'd kill a common person)",
    ],
  },
  {
    id: 'seeker-attuned',
    name: 'Attuned',
    selectable: true,
    triggerOverride: 'When you **Seek Insight**, you can always ask, "What here is infused with magic?" for free, even on a 6-.',
  },
  {
    id: 'seeker-conduit-of-power',
    name: 'Conduit of Power',
    selectable: true,
    uses: 3,
    triggerOverride: 'When you **would mark a Consequence from a major arcanum**, you can mark 1 box here instead, with no negative effect. (These marks never clear.)',
  },
  {
    id: 'seeker-countermeasures',
    name: 'Countermeasures',
    selectable: true,
    triggerOverride: 'When you **witness a magical effect**, you may ask the GM, "how can this be countered or interrupted?" and get an honest answer. You or an ally gain advantage on your next roll to act on the answer.',
  },
  {
    id: 'seeker-everything-bleeds',
    name: 'Everything Bleeds',
    selectable: true,
    triggerOverride: "When you **exploit an unnatural foe's specific weakness or vulnerability**, deal +1d6 damage.",
  },
  {
    id: 'seeker-everything-burns',
    name: 'Everything Burns',
    selectable: true,
    triggerOverride: 'When you **inspect a work of artifice or magic for a fatal flaw**, roll +INT: **on a 7+**, the GM will reveal the best way to destroy/sabotage it; **on a 10+**, you or an ally also gain advantage to act on the info.',
  },
  { ...IMPROVED_STAT_BASE, id: 'seeker-improved-stat' },
  {
    id: 'seeker-initiate-of-the-secret-arts',
    name: 'Initiate of the Secret Arts',
    selectable: true,
    takes: 2,
    requiresLevel: 2,
    body: 'You have a "Sacred Pouch" (3 Stock, *magical*), as per the Blessed, but with no remarkable traits. Each time you take this move, choose a Blessed move for which you otherwise qualify. (You can\'t take Improved Stat or Superior Stat.)',
  },
  {
    id: 'seeker-lets-make-a-deal',
    name: "Let's Make a Deal",
    selectable: true,
    triggerOverride: 'When you **Seek Insight**, add "What do they really want or need?" to the list of questions. When you **Persuade by offering them something that you know they want or need**, treat a 7-9 as a 10+.',
  },
  {
    id: 'seeker-logbook',
    name: 'Logbook',
    selectable: true,
    uses: 2,
    triggerOverride: 'You have a logbook (2 uses, *slow*) that doesn\'t take up space in your inventory. When you (and only you) **consult your logbook and expend a use**, you can ignore a Know Things roll you just made and treat the result as a 10+. When *the Seasons Change*, reset your logbook to 2 uses.',
  },
  {
    id: 'seeker-magpie',
    name: 'Magpie',
    selectable: true,
    triggerOverride: 'When you **Have What You Need**, you can produce something strange, specific, maybe even valuable or a little bit magical, but if you do, tell us where you got it and 2 of the following:',
    list: [
      "How it's not quite right, but maybe it'll do?",
      'The trouble you caused back home by getting it',
      'Why using it will draw unwanted attention',
      "That it's the only thing like this that you've got, and why it'll only work the one time",
    ],
  },
  {
    id: 'seeker-never-at-a-loss',
    name: 'Never at a Loss',
    selectable: true,
    triggerOverride: "When you **Know Things and roll a 6-**, you may choose to not mark XP. If you don't mark XP, the worst that happens is that the GM tells you nothing interesting or useful about the subject, but instead tells you how you could learn more.",
  },
  {
    id: 'seeker-polyglot',
    name: 'Polyglot',
    selectable: true,
    triggerOverride: 'When you **first encounter a living language in play**, describe your proficiency with it (if any) and how you came to acquire it.',
    body: 'When you **Know Things about any script, text, runes or symbols that you encounter**, you have advantage.',
  },
  {
    id: 'seeker-cryptologist',
    name: 'Cryptologist',
    selectable: true,
    requires: ['seeker-polyglot'],
    triggerOverride: 'When you **study encoded, forgotten, or arcane marks or writing**, roll +INT: **on a 10+**, you can fully decipher them in just a few minutes; **on a 7-9**, you get the gist in a few minutes, but fully deciphering them will take an hour or so.',
  },
  {
    id: 'seeker-quick-study',
    name: 'Quick Study',
    selectable: true,
    triggerOverride: 'When you **study something magical that should take months to understand**, it instead takes mere weeks. If it should take weeks, it takes days. If it should take days, it takes only a few hours.',
  },
  {
    id: 'seeker-safety-first',
    name: 'Safety First',
    selectable: true,
    uses: 2,
    triggerOverride: 'When you **spend an hour or so preparing your mystical defenses**, hold 2 Protection. When you **are affected by harmful magic**, spend 1 Protection either to gain advantage on any roll to resist it or to halve its damage/effects.',
  },
  {
    id: 'seeker-sage-advice',
    name: 'Sage Advice',
    selectable: true,
    triggerOverride: 'When **another PC asks you for guidance**, they get advantage on their next roll to follow your advice.',
  },
  {
    id: 'seeker-arcane-adept',
    name: 'Arcane Adept',
    selectable: true,
    requiresLevel: 6,
    triggerOverride: 'When you **wish to invent a spell or magical effect**, detail its workings with the GM and Make a Plan to invent it. If you like, pick one requirement and ask the GM to provide an alternative (for example "first you must ___" could become "first you must ___, or it will take months").',
  },
  {
    id: 'seeker-deep-insight',
    name: 'Deep Insight',
    selectable: true,
    requiresLevel: 6,
    requires: ['seeker-attuned'],
    triggerOverride: 'When you **Seek Insight about something magical**, you may ask one additional question, not limited to the list. Even on a 6-, you get to ask this question.',
  },
  {
    id: 'seeker-improvise',
    name: 'Improvise',
    selectable: true,
    requiresLevel: 6,
    requires: ['seeker-quick-study'],
    triggerOverride: "When you **wish to use an arcanum's move or option without having unlocked it**, ask the GM what fool risk(s) it requires and/or what consequence(s) you'll incur. If you go for it, roll +INT: **on a 7+**, you get it to work this once — trigger the move or use the option as if you'd unlocked it; and **on a 10+**, also mark one step towards unlocking the arcanum's mysteries.",
  },
  { ...SUPERIOR_STAT_BASE, id: 'seeker-superior-stat' },
  {
    id: 'seeker-mind-over-magic',
    name: 'Mind Over Magic',
    selectable: true,
    requiresLevel: 6,
    triggerOverride: 'When you **roll to study or use an arcanum**, you can roll +INT instead of the stat you\'d normally roll.',
  },
  {
    id: 'seeker-overchannel',
    name: 'Overchannel',
    selectable: true,
    requiresLevel: 6,
    requires: ['seeker-conduit-of-power'],
    triggerOverride: 'When you **would mark a Consequence from a major arcanum**, you may mark a debility instead.',
  },
  {
    id: 'seeker-proof-against-detection',
    name: 'Proof Against Detection',
    selectable: true,
    requiresLevel: 6,
    requires: ['seeker-safety-first'],
    triggerOverride: "When you **hold Protection**, you can't be scried upon or sensed by magical means, and have advantage to Defy Danger by being stealthy.",
  },
];
